### ISSUE TITLE
[TODO]: Create more models

### ISSUE THREAD

**Issue by retraigo** [retraigo/la-classy#1]
## The following models are in the roadmap:**

**Regression:**
- [x] Multiple Linear Regression
- [ ] Support Vector Regressor
- [ ] Decision Tree Classifier
- [ ] Random Forest Classifier
- [ ] Polynomial Regression

**Classification:**
- [x] Softmax Regression
- [ ] Decision Tree Classifier
- [ ] Random Forest Classifier
- [ ] Support Vector Classifier
- [ ] Naive Bayes Classifier
