### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by retraigo** [retraigo/la-classy#6]
The following tasks need to be completed before the release of v1.0.0:

- [x] Fix `predict()` methods.
- [x] Add SAG solver.
- Write examples for:
  - [x] OLS Linear Regression
  - [x] SGD Logistic Regression (multinomial)
  - [x] SAG Linear SVM 
- [x] Add convergence criteria.
- [x] Fix regularization.
